import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: {
  modal: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* loading, template, error handling error*/}
        {props.modal}
        {props.children}
        {/* api => application programming interface
            software => software, api
            REST API, Representational State Transfer Application programming interface
            
            source=> user/2
            method=> GET, PUT, PATCH, DELETE, POST, OPTION
            status code=>  200, 400, 500
        */}
      </body>
    </html>
  );
}
